# Generated by Django 5.2.6 on 2025-09-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hangarin_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='statusstatus',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress ', 'In Progress'), ('Completed', 'Completed')], max_length=50),
        ),
    ]
