# Generated by Django 5.2.6 on 2025-09-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hangarin_app', '0002_rename_statusstatus_subtask_status_alter_task_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name': 'Priority', 'verbose_name_plural': 'Priorities'},
        ),
    ]
